name: Build branch

on:
  push:

jobs:
  build:
    name: Test - Unit & Integration
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'liberica'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B package -P github
        env:
          USER_NAME: ${{ secrets.USER_NAME }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          PERPLEXITY_API_KEY: test-value
